version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - .github/actions/generate-action-code
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried

  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Berlin
    assignees:
      - ffried
    reviewers:
      - ffried
