name: Swift Package Documentation Generator
description: Generates documentation for a Swift package using docc.
author: ser.soft GmbH
inputs:
  package-path:
    description: The path to the package.
    required: true
    default: ${{ github.workspace }}
  package-version:
    description: The version to use for this package.
    required: false
  enable-inherited-docs:
    description: Whether to enable inherited docs.
    required: true
    default: 'false'
  enable-index-building:
    description: Enables index building.
    required: true
    default: 'false'
  platform:
    description: Specify information about the current release of a platform. See docc `--platform`.
    required: false
  checkout-path:
    description: The root path of the repository's checkout. Defaults to the workspace.
    required: false
    default: ${{ github.workspace }}
  repository-service:
    description: The service to use for the repository. Must be supported by docc. Defaults to GitHub.
    required: false
    default: 'github'
  repository-base-url:
    description: The base URL of the repository. Defaults to the current repository.
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref || github.sha }}
  transform-for-static-hosting:
    description: Enables the static hosting transformation.
    required: true
    default: 'false'
  hosting-base-path:
    description: The hosting base path to use.
    required: false
  other-docc-arguments:
    description: Further (newline-separated) docc arguments.
    required: false
  targets:
    description: A list of targets separated by newline. If not given, all targets are built. Ignored if `use-xcodebuild` is `true`.
    required: false
  disable-automatic-documentation-combination:
    description: If not set, this action will automatically use `enable-experimental-combined-documentation` if more than one target is passed. Ignored if `use-xcodebuild` is `true`.
    required: true
    default: 'false'
  use-xcodebuild:
    description: Tells the action to use xcodebuild (instead of `swift package`). Use `xcodebuild-scheme` and `xcodebuild-destination` to further customize the xcodebuild invocation.
    required: true
    default: 'false'
  xcodebuild-scheme:
    description: The scheme to use for the xcodebuild invocation. Required if `use-xcodebuild` is true.
    required: false
  xcodebuild-destination:
    description: The destination to use for the xcodebuild invocation. Required if `use-xcodebuild` is true.
    required: false
  other-xcodebuild-arguments:
    description: Further (newline-separated) xcodebuild arguments.
    required: false
  output:
    description: The path to the output folder.
    required: false
runs:
  using: node24
  main: dist/index.js
branding:
  color: orange
  icon: book
